version: "3"
services:
  app:
    build:
      context: src/app/
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      APP_LOCAL_RUN: true
  transcription-api:
    build:
      context: src/transcription-api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  nlp-api:
    build:
      context: src/nlp-api/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
